### ISSUE TITLE
No mock implementation of Resque#remove_delayed_job_from_timestamp

### ISSUE THREAD

**Issue by archit** [justinweiss/resque_unit#26]
resque-scheduler v2.0.0.f added a Resque#remove_delayed_job_from_timestamp [see here](https://github.com/bvandenbos/resque-scheduler/blob/master/HISTORY.md). However resque_unit doesn't mock/stub that out.

**Comment by olliebennett** [comment]
Assume this can be closed since this mock was implemented in https://github.com/justinweiss/resque_unit/commit/3dd4ae2159e5c916e6af3bfd5068a945e0dc12ea ?

**Comment by justinweiss** [comment]
Good catch, thanks!
