### ISSUE TITLE
Resque.info gives error

### ISSUE THREAD

**Issue by chainsingh** [justinweiss/resque_unit#40]
When resque and resque_unit both are used, in that case Resque.info does not work and return the error "RuntimeError: can't add a new key into hash during iteration from /home/dev/.gem/ruby/2.2.0/gems/resque_unit-0.4.8/lib/resque_unit/resque.rb:16:in `block in reset!`".  I debugged it and found that in the above scenario,  queues method called in info method does not go to the "intended method in the same file" but rather to the one defined in resque_unit/resque.rb line: 22" and hence fails. I am using resque-1.25.2 and resque_unit-0.4.8.
Please resolve this issue.

**Comment by justinweiss** [comment]
Is this in development, production, or in test?

**Comment by chainsingh** [comment]
This is in test.

**Comment by justinweiss** [comment]
Thanks. It looks like that method was never stubbed by `resque_unit`. I'll take a look when I get a chance.

**Comment by justinweiss** [comment]
Hey, I just released a beta that should fix the issue -- if you want, try `v1.0.0.beta.1`.
