### ISSUE TITLE
"Can't add a new key into hash during iteration" Error

### ISSUE THREAD

**Issue by WillTaylor22** [justinweiss/resque_unit#47]

**Comment by WillTaylor22** [comment]
The following line raises the error in the title in Ruby >=1.9

@queue = Hash.new { |h, k| h[k] = [] }

It's in lib/resque_unit/resque.rb

**Comment by justinweiss** [comment]
That's strange -- I've never seen this one before. Could you describe some of the context around what you're trying to do?

**Comment by WillTaylor22** [comment]
I hope this helps!
http://stackoverflow.com/questions/32872659/redis-iteratively-creating-broken-queues-similar-to-failed?noredirect=1#comment53577449_32872659

It's fixed now on my end, so I'm not sure what it was

**Comment by justinweiss** [comment]
OK. I'm going to close this, because that line of code won't even exist in the new version :-)
